language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-23
script:
  - ./gradlew clean assembleDebug